[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["templates"]

[project]
name = "tilemaker"
version = "0.0.1a1"
requires-python = ">=3.11"
dependencies = [
    "sqlmodel",
    "pydantic-settings",
    "numpy",
    "pydantic_numpy",
    "fastapi",
    "uvicorn",
    "matplotlib",
    "astropy",
]

[project.scripts]
tilemaker-fits-ingest = "tilemaker.scripts.fits:main"
tilemaker-remove = "tilemaker.scripts.remove:main"

[tool.ruff.lint]
extend-select = ["I"]
